// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rpxhlgtsojovyyxodtcr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJweGhsZ3Rzb2pvdnl5eG9kdGNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MTk4NTQsImV4cCI6MjA2NTM5NTg1NH0.7UoaZfVTbugy7H7JY2pglhvHa2NhwBmQ3qseWVc6fbw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);